version: '3'

services:
    sso:
        image: sso
        build:
            context: .
            dockerfile: src/Identity.SSO/Dockerfile
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        networks: 
            - identity_network

    api:
        image: api
        build:
            context: .
            dockerfile: src/Identity.API/Dockerfile
        ports:
            - "9000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        networks: 
            - identity_network

networks: 
    identity_network:
        driver: bridge